#ifndef LI_KEYMAP_H
#define LI_KEYMAP_H

typedef enum li_key {
	li_key_unknown,

	li_key_esc,
	li_key_f1,
	li_key_f2,
	li_key_f3,
	li_key_f4,
	li_key_f5,
	li_key_f6,
	li_key_f7,
	li_key_f8,
	li_key_f9,
	li_key_f10,
	li_key_f11,
	li_key_f12,

	li_key_tilde,
	li_key_minus,
	li_key_equal,
	li_key_backspace,

	li_key_tab,
	li_key_left_bracket,
	li_key_right_bracket,
	li_key_backslash,

	li_key_caps_lock,
	li_key_semicolon,
	li_key_apostrophe,
	li_key_enter,

	li_key_left_shift,
	li_key_comma,
	li_key_period,
	li_key_slash,
	li_key_right_shift,

	li_key_left_control,
	li_key_left_super,
	li_key_left_alt,
	li_key_space,
	li_key_right_alt,
	li_key_right_super,
	li_key_right_control,

	li_key_print,
	li_key_scroll_lock,
	li_key_pause,
	li_key_insert,
	li_key_home,
	li_key_page_up,
	li_key_delete,
	li_key_end,
	li_key_page_down,
	li_key_up,
	li_key_down,
	li_key_left,
	li_key_right,

	li_key_num_lock,
	li_key_num_divide,
	li_key_num_multiply,
	li_key_num_minus,
	li_key_num_7,
	li_key_num_8,
	li_key_num_9,
	li_key_num_plus,
	li_key_num_4,
	li_key_num_5,
	li_key_num_6,
	li_key_num_1,
	li_key_num_2,
	li_key_num_3,
	li_key_num_enter,
	li_key_num_0,
	li_key_num_period,

	li_key_0 = '0',
	li_key_1 = '1',
	li_key_2 = '2',
	li_key_3 = '3',
	li_key_4 = '4',
	li_key_5 = '5',
	li_key_6 = '6',
	li_key_7 = '7',
	li_key_8 = '8',
	li_key_9 = '9',
	li_key_char_a = 'a',
	li_key_char_b = 'b',
	li_key_char_c = 'c',
	li_key_char_d = 'd',
	li_key_char_e = 'e',
	li_key_char_f = 'f',
	li_key_char_g = 'g',
	li_key_char_h = 'h',
	li_key_char_i = 'i',
	li_key_char_j = 'j',
	li_key_char_k = 'k',
	li_key_char_l = 'l',
	li_key_char_m = 'm',
	li_key_char_n = 'n',
	li_key_char_o = 'o',
	li_key_char_p = 'p',
	li_key_char_q = 'q',
	li_key_char_r = 'r',
	li_key_char_s = 's',
	li_key_char_t = 't',
	li_key_char_u = 'u',
	li_key_char_v = 'v',
	li_key_char_w = 'w',
	li_key_char_x = 'x',
	li_key_char_y = 'y',
	li_key_char_z = 'z',
} li_key_t;

typedef enum li_button {
	li_button_unknown,
	li_button_left,
	li_button_middle,
	li_button_right,
} li_button_t;

typedef enum li_key_state {
	li_key_state_shift = 1,
	li_key_state_caps_lock = 2,
	li_key_state_control = 4,
	li_key_state_alt = 8,
	li_key_state_num_lock = 16,
	li_key_state_scroll_lock = 32,
	li_key_state_super = 64,
	li_button_state_left = 256,
	li_button_state_middle = 512,
	li_button_state_right = 1024,
} li_key_state_t;

li_key_t li_win_xlat_key(int keycode);
li_button_t li_win_xlat_button(int button);
li_key_state_t li_win_xlat_key_state(int state);

#endif
